lib/inn_web/router.ex
defmodule InnWeb.Router do
  use InnWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug CORSPlug, origin: "http://localhost:3000"
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug(Inn.Auth.AuthAccessPipeline)
  end

  scope "/", InnWeb do
    pipe_through :browser

    get "/", SessionController, :new
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/operator", InnWeb do
    pipe_through [:browser, :auth]

    get "/", OperatorController, :index
    resources "/sessions", SessionController, only: [:delete]
    delete "/inn/:id", OperatorController, :delete
    post "/block-ip", OperatorController, :block_ip
  end

  scope "/auth", InnWeb do
    pipe_through [:api]

    get "/token", AuthController, :token
  end

  # Other scopes may use custom stacks.
  # scope "/api", InnWeb do
  #   pipe_through :api
  # end
end

lib/inn_web/views/layout_view.ex
defmodule InnWeb.LayoutView do
  use InnWeb, :view
  import InnWeb.Router.Helpers
end

lib/inn_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Inn</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <%= csrf_meta_tag() %>
  </head>
  <body>
      <nav class="nav-extended">
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo center">Admin panel</a>
              <ul class="right hide-on-med-and-down">
                 <%= if current_user = assigns[:current_user] do %>
                    <li>
                      <%= link "Logout", to: session_path(@conn, :delete, current_user),
                                              method: "delete" %>
                    </li>
                  <% else %>
                     <li><%= link "Register", to: user_path(@conn, :new) %></li>
                     <li><%= link "Log In", to: session_path(@conn, :new) %></li>
                  <% end %>
            </ul>
          </div>
      </nav>
    <main role="main" class="container">
      <div class="row">
        <div class="col s12">
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        </div>
      </div>
        <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>